before_install:
- openssl aes-256-cbc -K $encrypted_af8ee76d875e_key -iv $encrypted_af8ee76d875e_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa

matrix:
  include:
  - os: osx
    language: generic
    install:
    - brew install qemu zoidbergwill/python/python35
    - brew install pygobject3 --with-python3 gtk+3
    - python3 -m pip install -r requirements-macos.txt
    - python3 -m pip install pyinstaller
    - pyinstaller pibox-installer-macos.spec
    - scp -o StrictHostKeyChecking=no -i travis_rsa dist/pibox-installer root@thiolliere.org:/var/www/html/public/pibox-binaries/pibox-installer-macos
  - os: linux
    language: python
    python: 3.5
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
          qemu
          qemu-system-arm
          python3-gi
          python3-gi-cairo
          gir1.2-gtk-3.0
          python3-dbus
    install:
    - pip install -r requirements-linux.txt
    - pip install pyinstaller
    - pyinstaller pibox-installer-linux.spec
    - scp -o StrictHostKeyChecking=no -i travis_rsa dist/pibox-installer root@thiolliere.org:/var/www/html/public/pibox-binaries/pibox-installer-linux
