before_install:
- pwd
- openssl aes-256-cbc -K $encrypted_af8ee76d875e_key -iv $encrypted_af8ee76d875e_iv -in pibox_installer_ci_rsa.travis_enc -out pibox_installer_ci_rsa -d
- chmod 600 pibox_installer_ci_rsa

matrix:
  include:
  - os: osx
    language: generic
    install:
    - brew install qemu zoidbergwill/python/python35
    - brew install pygobject3 --with-python3 gtk+3
    - python3 -m pip install -r requirements-macos.txt
    - python3 -m pip install pyinstaller
    - pyinstaller pibox-installer-macos.spec
    - scp -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa dist/pibox-installer pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/$(date +"%Y-%m-%d")/pibox-installer-macos
  - os: linux
    language: python
    python: 3.4
    dist: trusty
    sudo: required
    virtualenv:
      system_site_packages: true
    addons:
      apt:
        packages:
          qemu
          qemu-system-arm
          python3-gi
          python3-gi-cairo
          python3-cairo
          gir1.2-gtk-3.0
          libdbus-1-dev
          libdbus-glib-1-dev
    script:
    - pip3 install -r requirements-linux.txt
    - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
    - pyinstaller pibox-installer-linux.spec
    - scp -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa dist/pibox-installer pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/$(date +"%Y-%m-%d")/pibox-installer-linux
