version: 1.0.{build}

clone_folder: c:\projects\pibox-installer

image: Visual Studio 2015

build: off

platform:
  - x86
  - x64

install:
  # Install pygobject
  - appveyor DownloadFile "https://sourceforge.net/projects/pygobjectwin32/files/pygi-aio-3.18.2_rev12-setup_549872deadabb77a91efbc56c50fe15f969e5681.exe/download" -FileName "pygi-aio-setup.exe"
  - mkdir pygi-aio-setup
  - cd pygi-aio-setup
  - set SOURCEPATH=%cd%
  - 7z.exe x ..\pygi-aio-setup.exe
  - cd setup
  - del 7zr.exe
  - 7z.exe x ..\setup.exe
  - set GIR=True
  - rcmd.exe /c setup.bat C:\Python34 GTK
  - mklink /D C:\Python34\share C:\Python34\Lib\site-packages\gnome\share
  - cd ..\..
  - dir C:\Python34\Lib\site-packages\gi

  # Install gdk-pixbuf and add it to PATH because it is needed by pyinstaller
  - if %platform%==x86 C:\msys64\usr\bin\bash --login -c "pacman -S mingw-w64-i686-gdk-pixbuf2 --noconfirm"
  - if %platform%==x86 set PATH=%PATH%;C:\msys64\mingw32\bin
  - if %platform%==x64 C:\msys64\usr\bin\bash --login -c "pacman -S mingw-w64-x86_64-gdk-pixbuf2 --noconfirm"
  - if %platform%==x64 set PATH=%PATH%;C:\msys64\mingw64\bin

  # Install pyinstaller and requirements
  - cd C:\projects\pibox-installer
  - C:\Python34\python.exe -m pip install pyinstaller
  - C:\Python34\python.exe -m pip install -r requirements-windows.txt

  # Install qemu
  - mkdir "C:\Program Files\qemu"
  - cd "C:\Program Files\qemu"
  - if %platform%==x86 appveyor DownloadFile "https://qemu.weilnetz.de/w32/2017/qemu-w32-setup-20170418.exe" -FileName "qemu-setup.exe"
  - if %platform%==x64 appveyor DownloadFile "https://qemu.weilnetz.de/w64/2017/qemu-w64-setup-20170418.exe" -FileName "qemu-setup.exe"
  - 7z x qemu-setup.exe
  - dir "C:\Program Files\qemu"

  # Run pyinstaller and show warning
  - cd C:\projects\pibox-installer
  - if %platform%==x86 C:\Python34\python.exe C:\Python34\Scripts\pyinstaller-script.py pibox-installer-win32.spec
  - if %platform%==x64 C:\Python34\python.exe C:\Python34\Scripts\pyinstaller-script.py pibox-installer-win64.spec
  - type build\pibox-installer-windows\warnpibox-installer-windows.txt

artifacts:

  - path: dist\pibox-installer.exe
